server:
  port: 8085
spring:
  datasource:
    url: jdbc:h2:mem:pricingdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
