server:
  port: 8087
spring:
  application:
    name: fulfillment-service
  datasource:
    url: jdbc:h2:mem:fulfillmentdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  file:
    name: ${STEPFLOW_LOG_DIR:../temp/stepflow-logs}/${spring.application.name}.json
  structured:
    format:
      file: ecs
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB
